### ISSUE TITLE
Code doesn't compile on Travis

### ISSUE THREAD

**Issue by jdewinne** [xebialabs-community/xlr-github-plugin#1]
https://travis-ci.org/xebialabs-community/xlr-github-plugin/builds/51743970

**Comment by byaminov** [comment]
@jdewinne well, it cannot compile: it uses XLR libraries as dependencies, which requires a developer to unpack XLR distributions he/she has on his laptop and point to it using a Gradle parameter. So I don't think we can make it work on Travis.

**Comment by jdewinne** [comment]
@byaminov are you sure on this?
I think it only uses the XLR libraries when executing the tests. So that would mean, we could make the build work on Travis, (excluding the testing). correct?

**Comment by byaminov** [comment]
@jdewinne recently I moved some production classes that used XLR libraries away to [another plugin](https://github.com/xebialabs/xlr-development-workflow-plugin/blob/master/src/main/java/com/xebialabs/xlrelease/plugin/devworkflow/GitHubUtils.java#L47), but I plan to bring some of them back. So what you say is correct, but not for long.

But could you tell me what can we get from Travis?
