### ISSUE TITLE
Support WaitForMerge task

### ISSUE THREAD

**Issue by sushant-pradhan** [xebialabs-community/xlr-github-plugin#19]
Hello,

It would be nice to have a wait-for-pr-merge task just like we have in bitbucket [plugin](https://github.com/xebialabs-community/xlr-bitbucket-plugin/blob/d4770264e07f4f384f53784a28704ab36d666a04/src/main/resources/synthetic.xml#L89).

**Comment by zvercodebender** [comment]
Version 1.5.4 release with this feature
* [xlr-github-plugin-1.5.4.jar](https://github.com/xebialabs-community/xlr-github-plugin/releases/download/v1.5.4/xlr-github-plugin-1.5.4.jar)
