### ISSUE TITLE
Cannot build against 6.2.0

### ISSUE THREAD

**Issue by coderoshi** [xebialabs-community/xlr-github-plugin#3]
I don't know if the structure of XL Release has changed over the past two years, but this plugin is in dire need of an update. Issue after issue has arisen, and I'm finally blocked on this (why it's redefining `xlReleaseHome`, I can't say. But this file or directory does not exist.

```
A problem occurred configuring root project 'xlr-github-plugin'.
> /Applications/XL Release/xl-release-6.2.0-server does not exist or is not a folder
```

Thanks

**Comment by byaminov** [comment]
The current build code is tailored for having a folder with several XLR installations, unpacked from a ZIP distribution, have a look at this part of `build.gradle`:

    def xlrVersion = '4.7.2'
    def xlrsHome = propertyOrFail('xlReleasesHome',
        'Please specify location of XL Release versions on you disk using Gradle property "xlReleasesHome"')
    project.setProperty('xlReleaseHome', "$xlrsHome/xl-release-$xlrVersion-server")

So if you remove this part and set `xlReleaseHome = /Applications/XL Release` in your `gradle.properties`, then it should work.

On another note however what do you expect to get from this plugin? The current implementation is quite experimental and contains only one task: _Update content_ of a file in a GitHub repository. I would be glad to hear your use case.

**Comment by coderoshi** [comment]
The behavior you suggest means that property should only write if it isn't set in gradle.properties, so the last line should be replaced with:

```groovy
if (!project.hasProperty("xlReleaseHome")) {
  project.setProperty('xlReleaseHome', "$xlrsHome/xl-release-$xlrVersion-server")
}
```

That works. Thanks.

**Comment by byaminov** [comment]
I'm glad that it works for you, I added the change to the `build.gradle`. The integration test of this plugin however is not going to work anymore, as we removed the `server-test-kit` since a couple of versions ago.
